### ISSUE TITLE
[Perfil] Criar upload de imagem

### ISSUE THREAD

**Issue by modernfunkboss** [modernfunkboss/lpw-controlehoras-g2#32]
Criar o upload de imagem.
Na hora que subir, salvar o local da imagem em uma coluna no banco da tabela usuários. Chamado userAvatar.

depois no HTML sera assim
```HTML
<img src="{{ current_user.userAvatar }}" class="img-rounded">
```
Garantir alguns pontos

* Tipo de arquivo: JPG, PNG
* Armazenar no banco o local do arquivo
* Mensagens de erro caso o upload nao ocorra.

**Comment by lucioPintanel** [comment]
No html tem que ter um 'file select dialog'.
